



-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'ITEM'
-- 
-- ---

DROP TABLE IF EXISTS `ITEM`;
		
CREATE TABLE `ITEM` (
  `ITM_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `ITM_NAME` VARCHAR(50) NOT NULL,
  `ITM_PRICE` DOUBLE NOT NULL,
  `ITM_TYPE` VARCHAR(ITM_TYPE) NOT NULL,
  `ITM_DATE_CREATED` TIMESTAMP NOT NULL,
  `ITM_DATE_UPDATED` TIMESTAMP NOT NULL,
  `ITM_CREATED_BY_USER_ID` INTEGER NOT NULL,
  `ITM_UPDATED_BY_USER_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ITM_ID`)
);

-- ---
-- Table 'USER'
-- 
-- ---

DROP TABLE IF EXISTS `USER`;
		
CREATE TABLE `USER` (
  `USR_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `USR_FIRSTNAME` VARCHAR(50) NOT NULL,
  `USR_LASTNAME` VARCHAR(50) NOT NULL,
  `USR_USENAME` VARCHAR(50) NOT NULL,
  `USR_PASSOWORD` VARCHAR(50) NOT NULL,
  `USR_ROLE` VARCHAR NOT NULL DEFAULT '50',
  `USR_STATUS` INTEGER NOT NULL DEFAULT NULL,
  `USR_DATE_CREATED` TIMESTAMP NOT NULL,
  `USR_DATE_UPDATED` TIMESTAMP NOT NULL,
  `USR_CREATED_BY_USER_ID` INTEGER NULL,
  `USR_UPDATED_BY_USER_ID` INTEGER NULL,
  PRIMARY KEY (`USR_ID`)
);

-- ---
-- Table 'ORDER_STATUS'
-- 
-- ---

DROP TABLE IF EXISTS `ORDER_STATUS`;
		
CREATE TABLE `ORDER_STATUS` (
  `ORDST_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `ORDRST_VALUE` VARCHAR(50) NOT NULL,
  `ORDST_DATE_CREATED` TIMESTAMP NOT NULL,
  `ORDST_DATE_UPDATED` TIMESTAMP NULL DEFAULT NULL,
  `ORDST_CREATED_BY_USER_ID` INTEGER NOT NULL,
  `ORDST_UPDATED_BY_USER_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ORDST_ID`)
);

-- ---
-- Table 'ORDER'
-- 
-- ---

DROP TABLE IF EXISTS `ORDER`;
		
CREATE TABLE `ORDER` (
  `ORD_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `ORDR_STATUS_ID` INTEGER NOT NULL,
  `ORDR_TABLE_ID` INTEGER NOT NULL,
  `ORDR_BARMAN_ID` INTEGER NOT NULL,
  `ORD_DATE_CREATED` TIMESTAMP NOT NULL,
  `ORD_DATE_UPDATED` TIMESTAMP NOT NULL,
  `ORD_CREATED_BY_USER_ID` INTEGER NOT NULL,
  `ORD_UPDATED_BY_USER_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ORD_ID`)
);

-- ---
-- Table 'TABLE'
-- 
-- ---

DROP TABLE IF EXISTS `TABLE`;
		
CREATE TABLE `TABLE` (
  `TBL_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `TBL_NUMBER` INTEGER NOT NULL,
  `TBL_DATE_CREATED` TIMESTAMP NOT NULL,
  `TBL_DATE_UPDATED` TIMESTAMP NOT NULL,
  `TBL_CREATED_BY_USER_ID` INTEGER NOT NULL,
  `TBL_UPDATED_BY_USER_ID` INTEGER NOT NULL,
  PRIMARY KEY (`TBL_ID`)
);

-- ---
-- Table 'ORDER_TO_ITEM'
-- 
-- ---

DROP TABLE IF EXISTS `ORDER_TO_ITEM`;
		
CREATE TABLE `ORDER_TO_ITEM` (
  `ORDR_ID` INTEGER NOT NULL,
  `ITM_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ORDR_ID`)
);

-- ---
-- Foreign Keys 
-- ---

ALTER TABLE `ITEM` ADD FOREIGN KEY (ITM_CREATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `ITEM` ADD FOREIGN KEY (ITM_UPDATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `USER` ADD FOREIGN KEY (USR_CREATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `USER` ADD FOREIGN KEY (USR_UPDATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `ORDER_STATUS` ADD FOREIGN KEY (ORDST_CREATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `ORDER_STATUS` ADD FOREIGN KEY (ORDST_UPDATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (ORDR_STATUS_ID) REFERENCES `ORDER_STATUS` (`ORDST_ID`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (ORDR_TABLE_ID) REFERENCES `TABLE` (`TBL_ID`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (ORDR_BARMAN_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (ORD_CREATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `ORDER` ADD FOREIGN KEY (ORD_UPDATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `TABLE` ADD FOREIGN KEY (TBL_CREATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `TABLE` ADD FOREIGN KEY (TBL_UPDATED_BY_USER_ID) REFERENCES `USER` (`USR_ID`);
ALTER TABLE `ORDER_TO_ITEM` ADD FOREIGN KEY (ORDR_ID) REFERENCES `ORDER` (`ORD_ID`);
ALTER TABLE `ORDER_TO_ITEM` ADD FOREIGN KEY (ITM_ID) REFERENCES `ITEM` (`ITM_ID`);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `ITEM` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `USER` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ORDER_STATUS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ORDER` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `TABLE` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ORDER_TO_ITEM` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO `ITEM` (`ITM_ID`,`ITM_NAME`,`ITM_PRICE`,`ITM_TYPE`,`ITM_DATE_CREATED`,`ITM_DATE_UPDATED`,`ITM_CREATED_BY_USER_ID`,`ITM_UPDATED_BY_USER_ID`) VALUES
-- ('','','','','','','','');
-- INSERT INTO `USER` (`USR_ID`,`USR_FIRSTNAME`,`USR_LASTNAME`,`USR_USENAME`,`USR_PASSOWORD`,`USR_ROLE`,`USR_STATUS`,`USR_DATE_CREATED`,`USR_DATE_UPDATED`,`USR_CREATED_BY_USER_ID`,`USR_UPDATED_BY_USER_ID`) VALUES
-- ('','','','','','','','','','','');
-- INSERT INTO `ORDER_STATUS` (`ORDST_ID`,`ORDRST_VALUE`,`ORDST_DATE_CREATED`,`ORDST_DATE_UPDATED`,`ORDST_CREATED_BY_USER_ID`,`ORDST_UPDATED_BY_USER_ID`) VALUES
-- ('','','','','','');
-- INSERT INTO `ORDER` (`ORD_ID`,`ORDR_STATUS_ID`,`ORDR_TABLE_ID`,`ORDR_BARMAN_ID`,`ORD_DATE_CREATED`,`ORD_DATE_UPDATED`,`ORD_CREATED_BY_USER_ID`,`ORD_UPDATED_BY_USER_ID`) VALUES
-- ('','','','','','','','');
-- INSERT INTO `TABLE` (`TBL_ID`,`TBL_NUMBER`,`TBL_DATE_CREATED`,`TBL_DATE_UPDATED`,`TBL_CREATED_BY_USER_ID`,`TBL_UPDATED_BY_USER_ID`) VALUES
-- ('','','','','','');
-- INSERT INTO `ORDER_TO_ITEM` (`ORDR_ID`,`ITM_ID`) VALUES
-- ('','');

